### PR TITLE
Allows archived artifacts to be used in promotion publication process [FIXED JENKINS-34422]

### PR DESCRIPTION
**Pull request by mdkf**
Allows archived artifacts to be used in promotion publication process per: JENKINS-34422
Based off Publish Over plugin implimentation

### CODE REVIEW

**Comment by Greybird** [comment]
Hello,

I'm currently cut from internet, should be resolved quite soon.
Sorry for the delay in reviewing this PR.
Expert to have feedback as soon as I get a working conection.

Arnaud

**Comment by Greybird** [comment]
Hi,

Change is ok to me.
Can you please rebase it on top of the repo and solve conflicts ?
Also use [FIXED JENKINS-34422] prefix for the commit please (feel free to squash).

Thanks!

Arnaud

**Comment by mdkf** [comment]
Hi Arnaud,
 I integrated your changes. Thanks,
-Michael

**Comment by Greybird** [comment]
Thanks !

**Pull request merged**
